name-template: 'v1.0.$NEXT_PATCH_VERSION'
tag-template: 'v1.0.$NEXT_PATCH_VERSION'

template: |
  ## What's Changed
  $CHANGES

  **Full Changelog:** ${{ compare_url }}

change-template: '- $TITLE by @$AUTHOR'
no-changes-template: '- No changes'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Fixes'
    labels:
      - 'fix'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
